debug: false
# ??? ?? ???.
# ???? ??? ??? ?? ? ?? ?? ????? ? ??? ?? ?? ??? ??? ???? ? ??
management.endpoints.web.exposure.include: "*"
# actuactor? ???? ?? ?? ?? ??? ?? ??

logging:
  level: # ????? ???? ?? ??? ??
    com.fastcampus.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    # ????? ???? ?? ?? jpa? ???? ?? ??? ??? ??? ??? ??

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: miewone
    password: park8225
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
#    open-in-view: false
    defer-datasource-initialization: true
#    ???? ?????? ?? ? ?? ?.
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      # Spring boot? ???? ??  ????????? ???? ??
      hibernate.format_sql: true
      # ??? ????? ??? ??? ????? ?? ??
      hibernate.default_batch_fetch_size: 100
      #
  sql.init.mode: always
  h2:
    console:
      enabled: false
  data.rest:
    base-path: /api
    detection-strategy: annotated
#  thymeleaf3.decoupled-logic: true

---

#spring:
#  config.activate.on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driver-class-name: org.h2.Driver
#  sql.init.mode: always
#  test.database.replace: none #

# mysql에 가까운 환경으로 꾸며보겠다. h2는 호환성 모드를 지원하기 때문에